export const countries = [
    , "India",
    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
    "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia",
    "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
    "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)",
    "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica",
    "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
    "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
    "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
    "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea (North)", "Korea (South)", "Kosovo", "Kuwait",
    "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
    "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
    "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal",
    "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau",
    "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania",
    "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
    "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia",
    "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden",
    "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago",
    "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
    "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];


export const timeZoneData = [
    { "label": "(GMT+05:30) Asia/Kolkata", "value": "Asia/Kolkata" },
  { "label": "(GMT-12:00) Etc/GMT+12", "value": "Etc/GMT+12" },
  { "label": "(GMT-11:00) Pacific/Midway", "value": "Pacific/Midway" },
  { "label": "(GMT-10:00) Pacific/Honolulu", "value": "Pacific/Honolulu" },
  { "label": "(GMT-09:00) America/Anchorage", "value": "America/Anchorage" },
  { "label": "(GMT-08:00) America/Los_Angeles", "value": "America/Los_Angeles" },
  { "label": "(GMT-07:00) America/Denver", "value": "America/Denver" },
  { "label": "(GMT-06:00) America/Chicago", "value": "America/Chicago" },
  { "label": "(GMT-05:00) America/New_York", "value": "America/New_York" },
  { "label": "(GMT-04:00) America/Toronto", "value": "America/Toronto" },
  { "label": "(GMT-03:00) America/Sao_Paulo", "value": "America/Sao_Paulo" },
  { "label": "(GMT-02:00) Atlantic/South_Georgia", "value": "Atlantic/South_Georgia" },
  { "label": "(GMT-01:00) Atlantic/Azores", "value": "Atlantic/Azores" },
  { "label": "(GMT+00:00) Europe/London", "value": "Europe/London" },
  { "label": "(GMT+01:00) Europe/Berlin", "value": "Europe/Berlin" },
  { "label": "(GMT+02:00) Europe/Athens", "value": "Europe/Athens" },
  { "label": "(GMT+03:00) Asia/Riyadh", "value": "Asia/Riyadh" },
  { "label": "(GMT+03:30) Asia/Tehran", "value": "Asia/Tehran" },
  { "label": "(GMT+04:00) Asia/Dubai", "value": "Asia/Dubai" },
  { "label": "(GMT+04:30) Asia/Kabul", "value": "Asia/Kabul" },
  { "label": "(GMT+05:00) Asia/Karachi", "value": "Asia/Karachi" },
  { "label": "(GMT+05:45) Asia/Kathmandu", "value": "Asia/Kathmandu" },
  { "label": "(GMT+06:00) Asia/Dhaka", "value": "Asia/Dhaka" },
  { "label": "(GMT+06:30) Asia/Yangon", "value": "Asia/Yangon" },
  { "label": "(GMT+07:00) Asia/Bangkok", "value": "Asia/Bangkok" },
  { "label": "(GMT+08:00) Asia/Singapore", "value": "Asia/Singapore" },
  { "label": "(GMT+09:00) Asia/Tokyo", "value": "Asia/Tokyo" },
  { "label": "(GMT+09:30) Australia/Adelaide", "value": "Australia/Adelaide" },
  { "label": "(GMT+10:00) Australia/Sydney", "value": "Australia/Sydney" },
  { "label": "(GMT+11:00) Pacific/Guadalcanal", "value": "Pacific/Guadalcanal" },
  { "label": "(GMT+12:00) Pacific/Auckland", "value": "Pacific/Auckland" },
  { "label": "(GMT+13:00) Pacific/Tongatapu", "value": "Pacific/Tongatapu" }
];